#Application properties
spring:
  application:
    name: ccp

  #DB connection properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ccp
    url: jdbc:mysql://host.docker.internal:3306/ccp
    username: root
    password: root

  #JPA properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

#Actuator properties
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
